version: "3.9"
services:
  frontend:
    build:
      context: ..
      dockerfile: docs/Dockerfile.frontend
  backend:
    build:
      context: ..
      dockerfile: docs/Dockerfile.backend
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: prod
      POSTGRES_PASSWORD: prod
      POSTGRES_DB: cybernation
